server:
  port : 8080

spring:
  application:
    name: evetoolsuite-sde
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://sde-db/eve-sde}
    username: ${JDBC_DATABASE_USERNAME:eve}
    password: ${JDBC_DATABASE_PASSWORD:eve}
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        default_schema: evesde

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    de:
      ronnywalter:
        eve: INFO
    com.github.kagkarlsson: INFO
    org:
      hibernate:
        SQL: debug